### ISSUE TITLE
palette.json generation script availability ?

### ISSUE THREAD

**Issue by vpicavet** [riatelab/dicopal.js#1]
Hi,

Is the Python script used to generate palette.json available somewhere, I could not find it in the source code ?

**Comment by mthh** [comment]
Hi, It's actually not available (a bit messy because it was done quickly one day in the late afternoon, and included useless stuff and requests to a local triplestore containing the dicopal RDF vocabulary).
But I can remove the useless parts and put it on the repository if you want.

**Comment by mthh** [comment]
Here is a link : https://gist.github.com/mthh/c846dd04ae88a43b277f965808108bfd. I also added the link in the README.

**Comment by vpicavet** [comment]
> Hi, It's actually not available (a bit messy because it was done quickly one day in the late afternoon, and included useless stuff and requests to a local triplestore containing the dicopal RDF vocabulary). But I can remove the useless parts and put it on the repository if you want.

Great, thank you for publishing it. It would be great to have it incorporated in the source code, in order to be able to track changes. This can be very useful for other projects too !

**Comment by mthh** [comment]
> It would be great to have it incorporated in the source code

Indeed, in the end I thought so too and I'll push it in the source code in a few minutes.

Thanks for reaching out !

**Comment by mthh** [comment]
Done !
