### ISSUE TITLE
Generate unbalanced diverging schemes

### ISSUE THREAD

**Issue by joewdavies** [riatelab/dicopal.js#3]
Is it possible to generate an unbalanced diverging colour scheme?

For example: say I have a diverging scheme with 6 classes but instead of it diverging at the middle (between classes 3 and 4) I want it to diverge between classes 2 and 3.

We are using dicopal in our map making application IMAGE: https://gisco-services.ec.europa.eu/image/screen/home (once again, thank you for your work!)

And we often encounter use cases where unbalanced diverging schemes are required (for example a dataset with a vast majority of positive values and only a few negative values).

**Comment by mthh** [comment]
Thank you for your feedback! (btw IMAGE looks really good!)

It's a really good idea (which I'll also need for another project).

What kind of API would you like for this?

At the moment the API is relatively simple (and doesn't actually offer to transform the palettes as they are proposed by their creators).

Perhaps a 'second layer' of API might be needed to enable higher-level actions? 
Like generating unbalanced diverging schemes as you suggest (or like interpolating colors for sequential and divergent schemes if the user wants more classes than the original palette offers?)

**Comment by mthh** [comment]
Just a few thoughts on this: https://observablehq.com/@mthh/unbalanced-diverging-schemes-with-dicopal (I'm planning to test other things, but let me know if such an implementation could work for you)

**Comment by joewdavies** [comment]
This looks great! Excellent work - just what I was looking for.

**Comment by mthh** [comment]
Great, thanks ! I will make a new release next week with some new features, including this one.

**Comment by mthh** [comment]
It's been delayed by a few weeks :sweat: 
But I finally made a new release (0.6.0) with a new `getAsymmetricDivergingColors` function.

Don't hesitate to tell me if it doesn't meet your needs or if you think it could be improved!
