### ISSUE TITLE
Reverse asymmetric diverging colors

### ISSUE THREAD

**Issue by joewdavies** [riatelab/dicopal.js#6]
Good morning!

Me again :)

Would it be possible to add an option to getAsymmetricDivergingColors() which allows you to reverse the colour scheme?

For example, like the `reverse` argument that `getColors()` recieves.

Something like `getAsymmetricDivergingColors('RdYlBu', 7, 2, true, true, reverse)`;

Thanks!
Joe

**Comment by mthh** [comment]
Good idea, thanks!
I will include such a functionality in the next release.
